import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import css from "./page.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <nav className={css.nav}>
            <Link href="/birthday">Привітання до дня народження</Link>
            <Link href="/birthdayMom">Привітання до дня народження мами</Link>
            <Link href="/birthdayDad">Привітання до дня народження тата</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
